version: '3.3'

services:
  credit-card:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: credit-card/api
    environment:
      PROFILE: dev
      ADDITIONAL_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      DDL_AUTO: update
      JDBC_URL: jdbc:mysql://mysql-accounts:3306/db_credit_card
      JDBC_DRIVER: com.mysql.jdbc.Driver
      DATASOURCE_USERNAME: user
      DATASOURCE_PASSWORD: biv@user
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db_credit_card
    links:
      - db_credit_card
    networks:
      - api

  db_credit_card:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: froot
      MYSQL_DATABASE: db_credit_card
      MYSQL_USER: user
      MYSQL_PASSWORD: biv@user
      JDBC_URL: jdbc:mysql://db_credit_card:3306/db_credit_card?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&charactedEncoding=UTF-8&useTimezone=true&serverTimezone=UTC
      JDBC_DRIVER: com.mysql.cj.jdbc.Driver
    ports:
      - "3306:3306"
    command: --lower_case_table_names=2
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
    networks:
      - api
networks:
  api:
    driver: bridge