version: "3.9"

networks:
  creditcard-network:
    driver: bridge

services:
  creditcard-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: root
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      JDBC_URL: jdbc:mysql://db_api:3306/db_api?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&charactedEncoding=UTF-8&useTimezone=true&serverTimezone=UTC
      JDBC_DRIVER: com.mysql.cj.jdbc.Driver
    ports:
      - "3306:3306"
    command: --lower_case_table_names=2
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
    networks:
      - creditcard-network
  credit-card:
    image: birizv/creditcard-api
    command: ["/wait-for-it.sh", "creditcard-db:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: creditcard-db
    ports:
      - "8080:8080"
    networks:
      - creditcard-network
    depends_on:
      - creditcard-db